"""modify_gradutaion_requirements

Revision ID: 68ffd48be1d0
Revises: 9a08999b5c81
Create Date: 2026-05-22 23:49:29.867141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ffd48be1d0'
down_revision: Union[str, Sequence[str], None] = '9a08999b5c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement_rule', sa.Column('required_credits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirement_rule', 'required_credits')
    # ### end Alembic commands ###
