"""minor_change

Revision ID: 969d6f119160
Revises: 68ffd48be1d0
Create Date: 2026-05-26 12:28:03.162716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '969d6f119160'
down_revision: Union[str, Sequence[str], None] = '68ffd48be1d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_account', sa.Column('department_auxiliary1', sa.String(length=3), nullable=True))
    op.add_column('student_account', sa.Column('department_auxiliary2', sa.String(length=3), nullable=True))
    op.drop_constraint(op.f('fk_student_account_department_auxiliary_department'), 'student_account', type_='foreignkey')
    op.create_foreign_key(op.f('fk_student_account_department_auxiliary2_department'), 'student_account', 'department', ['department_auxiliary2'], ['department_id'])
    op.create_foreign_key(op.f('fk_student_account_department_auxiliary1_department'), 'student_account', 'department', ['department_auxiliary1'], ['department_id'])
    op.drop_column('student_account', 'department_auxiliary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_account', sa.Column('department_auxiliary', mysql.VARCHAR(length=3), nullable=True))
    op.drop_constraint(op.f('fk_student_account_department_auxiliary1_department'), 'student_account', type_='foreignkey')
    op.drop_constraint(op.f('fk_student_account_department_auxiliary2_department'), 'student_account', type_='foreignkey')
    op.create_foreign_key(op.f('fk_student_account_department_auxiliary_department'), 'student_account', 'department', ['department_auxiliary'], ['department_id'])
    op.drop_column('student_account', 'department_auxiliary2')
    op.drop_column('student_account', 'department_auxiliary1')
    # ### end Alembic commands ###
